server:
  port: 3000
spring:
  application:
    name: yyl-crowd-redis
  redis:
    host: 192.168.137.136
    port: 6379
    timeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka